# 要件定義: AlmaLinux更新検知Input Provider

metadata:
  title: "AlmaLinux更新検知Input Provider"
  feature: "almalinux-updates-provider"
  status: "draft"
  created: "2025-02-04"
  updated: "2025-02-04"
  version: "1.0.0"
  last_validated: null
  validation_passed: null
  complexity: "high"
  estimated-hours: 40
  dependencies: []

overview:
  description: |
    AlmaLinux更新検知Input Providerは、AlmaLinux（RHEL系）システムで利用可能なパッケージ更新を自動検知し、
    Okinaプロジェクトの標準データ形式で出力するコンポーネントです。
    セキュリティ更新、バグ修正、カーネル更新などを継続的に監視し、翁らしい静かで確実な監視を実現します。
  
  background: |
    システム管理者は、AlmaLinuxシステムのパッケージ更新を継続的に監視する必要があります。
    特にセキュリティ更新は迅速な対応が求められますが、手動での確認は負担が大きく、見逃しのリスクもあります。
    Okinaプロジェクトの一部として、AlmaLinux更新情報を自動検知し、標準形式で通知することで、
    システム管理者の負担を軽減し、セキュリティリスクを低減します。
  
  goals:
    - "AlmaLinuxパッケージの現在の状況と利用可能な更新を統合的に把握する"
    - "セキュリティ更新を優先的に識別し、CVE情報を含めて通知する"
    - "翁らしい静かな動作で、人間の判断を支援する情報を提供する"
    - "Okina標準形式で正規化されたデータを出力し、一貫した通知処理を実現する"
    - "エラーを適切に処理し、個別の操作が失敗しても監視を継続する"

acceptance-criteria:
  - id: "AC-001"
    title: "システム状況の統合的把握"
    priority: "high"
    type: "functional"
    description: |
      システム管理者として、AlmaLinuxパッケージの現在の状況と利用可能な更新を統合的に把握したい。
      正確な差分検知と適切な通知を実現するため。
    when: "更新スキャナーが実行されるとき"
    then: "現在インストールされているパッケージ情報（rpm -qa）と利用可能な更新（dnf check-update）の両方を取得し、各パッケージを「更新利用可能」「最近適用済み」「最新状態」のいずれかに分類しなければならない"
    examples:
      - input: "rpm -qa と dnf check-update の出力"
        output: "各パッケージの状態（update_available, recently_updated, current）"
  
  - id: "AC-002"
    title: "セキュリティ更新の優先識別"
    priority: "high"
    type: "security"
    description: |
      セキュリティ更新が利用可能なとき、それらを識別し、通常の更新より優先しなければならない。
      CVE情報が利用可能な場合は、CVE識別子と重要度評価を含めなければならない。
    when: "セキュリティ更新が検出されたとき"
    then: "セキュリティ更新を識別し、CVE情報と重要度を含めて優先的に処理しなければならない"
    examples:
      - input: "dnf updateinfo でセキュリティ更新を検出"
        output: "is_security=true, cve_ids=['CVE-2023-12345'], priority='high'"
  
  - id: "AC-003"
    title: "カーネル更新の再起動フラグ"
    priority: "high"
    type: "functional"
    description: |
      カーネルやシステム重要更新が検出されたとき、システム再起動が必要であることをマークしなければならない。
    when: "カーネル関連パッケージが検出されたとき"
    then: "requires_rebootフラグをtrueに設定しなければならない"
    examples:
      - input: "kernel-5.14.0-362.8.1.el9_3"
        output: "requires_reboot=true"
  
  - id: "AC-004"
    title: "最近適用された更新の記録"
    priority: "medium"
    type: "functional"
    description: |
      最近適用された更新（過去7日以内）を検出したとき、適用済み情報として記録しなければならない。
    when: "過去7日以内に適用された更新を検出したとき"
    then: "status='recently_updated'として記録しなければならない"
    examples:
      - input: "install_date='2025-02-03', current_date='2025-02-04'"
        output: "status='recently_updated'"
  
  - id: "AC-005"
    title: "Okina標準形式への変換"
    priority: "high"
    type: "functional"
    description: |
      Okinaシステムコンポーネントとして、標準形式で正規化された更新データを受信したい。
      通知を一貫して処理・ルーティングするため。
    when: "更新データが処理されるとき"
    then: "okina.item.v1スキーマに変換し、JSON Lines形式で標準出力に書き出さなければならない"
    examples:
      - input: "SystemUpdateStatus オブジェクト"
        output: "okina.item.v1 JSON形式"
  
  - id: "AC-006"
    title: "一意識別子の生成"
    priority: "high"
    type: "functional"
    description: |
      一意識別子を生成するとき、「almalinux:package:version:status」形式でIDを作成しなければならない。
      statusは"update"または"applied"。
    when: "データを出力するとき"
    then: "almalinux:package:version:status形式のIDを生成しなければならない"
    examples:
      - input: "kernel, 5.14.0-362.8.1, update_available"
        output: "almalinux:kernel:5.14.0-362.8.1.el9_3:update"
      - input: "kernel, 5.14.0-362.8.1, recently_updated"
        output: "almalinux:kernel:5.14.0-362.8.1.el9_3:applied"
  
  - id: "AC-007"
    title: "状態変化の差分検知"
    priority: "high"
    type: "functional"
    description: |
      同一パッケージが「更新利用可能」から「適用済み」に変化したとき、IDを変更して差分検知を可能にしなければならない。
    when: "パッケージ状態が変化したとき"
    then: "異なるIDとタグを使用して差分検知を可能にしなければならない"
    examples:
      - input: "update_available → recently_updated"
        output: "ID変更: :update → :applied"
  
  - id: "AC-008"
    title: "エラー処理の継続性"
    priority: "high"
    type: "non-functional"
    description: |
      システム運用者として、プロバイダーがエラーを適切に処理してほしい。
      個別の操作が失敗しても監視が継続されるため。
    when: "dnfコマンドが失敗したとき"
    then: "エラーをログに記録し、利用可能なデータで継続しなければならない"
    examples:
      - input: "dnf check-update タイムアウト"
        output: "エラーログ記録、rpm -qa データで継続"
  
  - id: "AC-009"
    title: "設定ファイルの読み込み"
    priority: "medium"
    type: "functional"
    description: |
      システム管理者として、プロバイダーの動作を設定したい。
      環境のニーズに応じて監視をカスタマイズするため。
    when: "設定が読み込まれるとき"
    then: "YAML設定ファイルから設定を読み取り、設定ファイルが存在しない場合はデフォルト値を使用しなければならない"
    examples:
      - input: "config.yml が存在"
        output: "設定値を読み込み"
      - input: "config.yml が不在"
        output: "デフォルト値を使用"
  
  - id: "AC-010"
    title: "翁らしい静かな動作"
    priority: "high"
    type: "non-functional"
    description: |
      Okinaユーザーとして、プロバイダーが「翁らしい」設計哲学に従ってほしい。
      静かに動作し、意思決定を人間に委ねるため。
    when: "通常動作中"
    then: "不要な出力なしで静かに動作し、推奨アクションを行わず、情報のみを提示しなければならない"
    examples:
      - input: "正常実行"
        output: "標準エラー出力なし、JSON Lines のみ標準出力"
  
  - id: "AC-011"
    title: "dnf/rpm出力の解析"
    priority: "high"
    type: "functional"
    description: |
      開発者として、dnfコマンドとrpmコマンドの出力を確実に解析したい。
      正確な更新情報と現在の状況を抽出するため。
    when: "rpm -qa / dnf check-update 出力を解析するとき"
    then: "パッケージ名、バージョン、リポジトリ、インストール日時を正確に抽出しなければならない"
    examples:
      - input: "rpm -qa 出力"
        output: "パッケージ名、バージョン、インストール日時"
      - input: "dnf check-update 出力"
        output: "パッケージ名、利用可能なバージョン、リポジトリ"
  
  - id: "AC-012"
    title: "cronスケジューリング統合"
    priority: "medium"
    type: "non-functional"
    description: |
      システム統合者として、プロバイダーがcronスケジューリングとシームレスに統合してほしい。
      自動監視を実行するため。
    when: "cronで実行されるとき"
    then: "合理的な時間制限内で完了し、標準Unix終了コードで終了しなければならない"
    examples:
      - input: "cron実行"
        output: "終了コード 0（成功）または 1（エラー）"
  
  - id: "AC-013"
    title: "dnfタイムアウト制御"
    priority: "high"
    type: "non-functional"
    description: |
      システム運用者として、dnfコマンドがスタック（ハング）した場合に適切に対処してほしい。
      システム全体の停止を回避し、安定した監視を継続するため。
    when: "dnfコマンドを実行するとき"
    then: "設定可能なタイムアウト（デフォルト5分）を設定し、タイムアウト時はプロセスを適切に終了しなければならない"
    examples:
      - input: "dnf check-update 実行"
        output: "5分でタイムアウト、プロセス終了、エラーログ記録"
  
  - id: "AC-014"
    title: "実行間隔の設定"
    priority: "medium"
    type: "non-functional"
    description: |
      システム運用者として、適切な実行間隔でプロバイダーが動作してほしい。
      システムリソースを無駄にせず、必要な情報を確実に取得するため。
    when: "デフォルト実行間隔として"
    then: "1日1回の実行を想定して設計され、最短1時間から最長7日までの範囲で設定を受け入れなければならない"
    examples:
      - input: "cron設定"
        output: "0 9 * * * （毎日午前9時）"
  
  - id: "AC-015"
    title: "エラー時の静かな処理"
    priority: "high"
    type: "non-functional"
    description: |
      システム運用者として、エラー発生時にシンプルで明確な対応をしてほしい。
      複雑な自動復旧ではなく、静かにログ記録して人間の判断に委ねるため。
    when: "エラーが発生したとき"
    then: "詳細なエラー情報をログファイルに記録し、自動リトライや自動修復を行わず、次回実行時の自然な復旧に委ねなければならない"
    examples:
      - input: "dnf タイムアウトエラー"
        output: "error.log に記録、終了コード 1、次回実行で自動復旧"

non-functional-requirements:
  performance:
    - "dnfコマンド実行時間: 5分以内（タイムアウト設定）"
    - "全体処理時間: 10分以内"
    - "メモリ使用量: 100MB以内"
  
  reliability:
    - "エラー時も処理を継続（継続可能エラーの場合）"
    - "データ損失がない（ログファイルへの確実な記録）"
    - "次回実行時の自動復旧（自然な回復）"
  
  maintainability:
    - "YAML設定ファイルで管理"
    - "新しいパッケージタイプを簡単に追加できる"
    - "テストカバレッジ90%以上"
  
  usability:
    - "エラーメッセージは日本語で分かりやすく"
    - "設定サンプルを提供"
    - "cron設定例を提供"

constraints:
  - "AlmaLinux 9専用（RHEL系Linux）"
  - "Python 3.10+以上"
  - "dnf, rpm コマンドが利用可能"
  - "Okina標準形式（okina.item.v1）に準拠"

assumptions:
  - "システム管理者は日本語話者"
  - "cronまたは手動で実行される"
  - "dnf/rpmコマンドの出力形式は標準的"
  - "ネットワーク接続が利用可能（リポジトリアクセス）"

risks:
  - risk: "dnfコマンドがハングする可能性"
    mitigation: "タイムアウト制御（デフォルト5分）を実装"
    probability: "medium"
    impact: "high"
  
  - risk: "dnf/rpm出力形式の変更"
    mitigation: "形式警告をログに記録、柔軟な解析ロジック"
    probability: "low"
    impact: "high"
  
  - risk: "ネットワーク接続の不安定性"
    mitigation: "指数バックオフで再試行（最大3回）"
    probability: "medium"
    impact: "medium"
  
  - risk: "ディスク容量不足"
    mitigation: "ログローテーション設定、適切なエラー処理"
    probability: "low"
    impact: "medium"

scope:
  in-scope:
    - "AlmaLinuxパッケージ更新の検知"
    - "現在のパッケージ状況と利用可能な更新の統合分析"
    - "セキュリティ更新の優先識別"
    - "Okina標準形式への変換"
    - "dnf/rpmコマンドのタイムアウト制御"
    - "翁らしい静かなエラー処理"
    - "YAML設定ファイルによるカスタマイズ"
  
  out-of-scope:
    - "自動的なパッケージ更新の適用（ユーザーが手動で実行）"
    - "リアルタイム監視（1日1回の定期実行）"
    - "他のLinuxディストリビューション対応（AlmaLinux専用）"
    - "GUI管理ツール（CLI専用）"
    - "通知機能（Okinaが担当）"

success-metrics:
  quantitative:
    - "テストカバレッジ90%以上を達成"
    - "全既存テストがパス"
    - "プロパティテスト100回以上の反復実行"
    - "dnfタイムアウト制御が確実に動作"
  
  qualitative:
    - "システム管理者が更新状況を正確に把握できる"
    - "セキュリティ更新が見逃されない"
    - "翁らしい静かな動作が実現される"
    - "Okinaとの統合がスムーズ"
